export { default as Home } from './Home/Home';
export { default as HomeEvent } from './Events-News/Home'
export { default as Events } from './Events-News/Events'
export { default as News } from './Events-News/News'
export { default as EventDetail } from './Events-News/EventDetail'
export { default as NewsDetail } from './Events-News/NewsDetail'
export { default as EventRegistration } from './Events-News/EventRegistration'
export { default as VanHoaLichSu } from './Events-News/VanHoaLichSu'
export { default as HeroesList } from './Events-News/HeroesList'
export { default as PhanTichGocNhin } from './Events-News/PhanTichGocNhin'
export { default as Forum } from './Events-News/Forum'
export { default as GiaoDuc } from './GiaoDuc';
export { default as BaiGiangMinhHoa } from './BaiGiangMinhHoa';
export { default as TaiLieuBaiGiang } from './TaiLieuBaiGiang';
export { default as BaiGiangDetail } from './BaiGiangDetail';
export { default as TaiLieuDetail } from './TaiLieuDetail';
export { default as BaiHocMinhHoaDetail } from './BaiHocMinhHoaDetail';
export { default as VirtualChronicle } from './VirtualChronicle';
export { default as CongNghe } from './CongNghe';
export { default as TaoTranh } from './TaoTranh';
export { default as TraiNghiem } from './TraiNghiem';
export { default as ChiTietTranh } from './Store/ChiTietTranh';
export { default as DonatUngHo } from './Store/DonatUngHo';
export { default as MuaTranhIn } from './Store/MuaTranhIn';
export { default as ThanhVienVIP } from './Store/ThanhVienVIP';
export { default as ThankYou } from './Store/ThankYou';
