export { default as Home } from './Home'
export { default as Events } from './Events'
export { default as News } from './News'
export { default as EventDetail } from './EventDetail'
export { default as NewsDetail } from './NewsDetail'
export { default as EventRegistration } from './EventRegistration'
export { default as VanHoaLichSu } from './VanHoaLichSu'
export { default as PhanTichGocNhin } from './PhanTichGocNhin'
export { default as Forum } from './Forum'
export { default as Settings } from './accountAndSupport/Settings'
export { default as Guides } from './accountAndSupport/Guides'
export { default as Contact } from './accountAndSupport/Contact'

// New Pages
export { default as ContactPage } from './ContactPage'
export { default as FriendsPage } from './FriendsPage'
export { default as InfoPage } from './InfoPage'
export { LoginPage, RegisterPage } from './auth'
